TSK-7092: files v2 adjustments
blinkops/blink-sdk pull request #63
Opened 2022-09-05 19:03 UTC by abramov-blink

2022-09-06 06:17 UTC, itsofirblink requested changes

2022-09-06 06:17 UTC, itsofirblink commented on plugin/config/aws.go
> +func SetAwsEnv(accessKeyId, accessSecretKey, sessionToken string) (func(), error) {
i think that's a big no no, don't set env variables with credentials on the root user.
You can create object `credentials` to pass to all AWS SDK functions

2022-09-06 06:17 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	}
i don't understand why won't you just use the `else` part with 
```golang
downloader.Concurrency = numRequests
```
or something like that, that's basically the same

2022-09-06 06:17 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	})
extract config to a variable

2022-09-06 06:17 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	}); err != nil {
extract iterator to a variable

2022-09-06 06:17 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	})
extract config to variable

2022-09-06 06:17 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +		Objects: uploadObjects,
extract iterator to a variable

2022-09-06 07:50 UTC, abramov-blink commented on plugin/config/aws.go
> +func SetAwsEnv(accessKeyId, accessSecretKey, sessionToken string) (func(), error) {
I agree. Done

2022-09-06 07:50 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	}
Done (something like that.. like we talked about :) )

2022-09-06 07:50 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	})
Done

2022-09-06 07:50 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	}); err != nil {
Done

2022-09-06 07:50 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	})
Done

2022-09-08 06:09 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	}
extract to function `getSession`

2022-09-08 06:09 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	}
use `getSession`

2022-09-08 06:09 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	}
use `getSession`

2022-09-08 06:10 UTC, itsofirblink commented on plugin/files/aws_provider.go
> +	}); err != nil {
extract `HeadObjectInput` to var

2022-09-08 06:10 UTC, itsofirblink commented on plugin/files/files.go
> +		return "", 0, fmt.Errorf("filename '%s' is invalid. Should only contain digits/numbers/'-'/'.'", fileName)
you can print out the regex

2022-09-08 06:14 UTC, itsofirblink commented on plugin/action_context.go
> +	if ok {
revese, `!ok` -> `return`

2022-09-08 09:32 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	}
Done

2022-09-08 09:32 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	}
Done

2022-09-08 09:32 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	}
Done

2022-09-08 09:32 UTC, abramov-blink commented on plugin/files/aws_provider.go
> +	}); err != nil {
Done

2022-09-08 09:32 UTC, abramov-blink commented on plugin/files/files.go
> +		return "", 0, fmt.Errorf("filename '%s' is invalid. Should only contain digits/numbers/'-'/'.'", fileName)
Done

2022-09-08 09:33 UTC, abramov-blink commented on plugin/action_context.go
> +	if ok {
Done

2022-09-08 09:35 UTC, itsofirblink approved these changes

2022-09-08 09:36 UTC, merged